---
- name: Install and enable MySQL service
  block:
  - name: Install MySQL server
    apt:
      name: mysql-server
      state: present
      update_cache: yes

  - name: Ensure MySQL service is running and enabled
    systemd:
      name: mysql
      state: started
      enabled: yes
  rescue:
  - name: Log installation failure
    debug:
      msg: "MySQL installation failed."

- name: Secure MySQL
  block:
  - name: Set root password for MySQL
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

  - name: Remove insecure default settings
    command: mysql_secure_installation
    args:
      creates: /etc/mysql/debian.cnf
    environment:
      MYSQL_PWD: "{{ mysql_root_password }}"

- name: Allow remote connections to MySQL
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address = 0.0.0.0"
    state: present
  notify:
    - Restart MySQL

- name: Open firewalli for MySQL, Allow all traffic from web server on port 3306
  ufw:
    rule: allow
    from_ip: "{{ hostvars['web']['ansible_host'] }}"
    port: 3306
    proto: tcp

- name: Create MySQL user and grant permissions
  mysql_user:
    name: root
    host: '%'
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  notify:
    - Restart MySQL
