---
- name: Install Apache web server
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache is running and enabled
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Create a sample index.php
  copy:
    dest: /var/www/html/index.php
    content: |
      <?php
      echo "Hello, this is a test PHP page!";
      phpinfo();
      ?>

- name: Ensure Apache can process PHP files
  apache2_module:
    name: php
    state: present
  notify:
    - Restart Apache

- name: Open firewall for HTTP and HTTPS
  ufw:
    rule: allow
    name: 'Apache Full'
    state: enabled


