---
# tasks file for roles/MySQL
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is running and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Set root password for MySQL
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Run mysql_secure_installation
  command: mysql_secure_installation
  args:
    creates: /etc/mysql/debian.cnf
  environment:
    MYSQL_PWD: "{{ mysql_root_password }}"

- name: Allow remote connections to MySQL
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address = 0.0.0.0"
    state: present
  notify:
    - Restart MySQL

- name: Open firewall for MySQL
  ufw:
    rule: allow
    port: 3306
    proto: tcp

- name: Create MySQL user and grant permissions
  mysql_user:
    name: root
    host: '%'
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  notify:
    - Restart MySQL
