---
- name: Install PHP and required extensions
  block:
    - name: Install PHP and required extensions
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      notify:
        - Restart Apache
  rescue:
    - name: Log installation failure
      debug:
        msg: "PHP installation failed."

