---
- name: Install and enable Apache web server
  block:
  - name: Install Apache web server
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Ensure Apache is running and enabled
    systemd:
      name: apache2
      state: started
      enabled: yes
  rescue:
    - name: Log installation failure
      debug:
        msg: "Apache installation failed."

- name: Create a sample index.php using a template
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: '0644'

- name: Ensure Apache can process PHP files
  apache2_module:
    name: php
    state: present
  notify:
    - Restart Apache

- name: Open firewall for HTTP and HTTPS
  ufw:
    rule: allow
    name: 'Apache Full'
    state: enabled


