# version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - backend-net
    env_file:
      - .env

  fastapi:
    container_name: fastapi
    build: ./src
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - backend-net
    env_file:
      - .env

  db:    
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:alpine3.21
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-net
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:

networks:
  backend-net:
    driver: bridge