- name: User Creation Based on OS and Version
  hosts: localhost
  tasks:
    - user:
        name: "{{ item }}"
        state: present
      loop:
        - devuser
        - qauser
      become: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 7
